export {default as Login} from './Login'
export {default as Resgister} from './Resgister'
export {default as Dashboard} from './Dashboard'
export {default as Cars} from './Cars'
export {default as Details} from './Details'